theme: jekyll-theme-dinky

title: <a href='/tiw8/2019'>TIW 8 — Ubicomp Web</a>
description: [<ul><li><a href='/tiw8/2019/#plan-du-cours'>Cours</a></li><li><a href='/tiw8/2019/#tp'>TP</a></li><li><a href='/tiw8/2019/evaluation'>Evaluation</a></li></ul>]
